# Generated by Django 4.2.9 on 2024-03-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_id',
            field=models.IntegerField(auto_created=True, blank=True, null=True, unique=True),
        ),
    ]
