# Generated by Django 4.2.9 on 2024-03-18 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nip', '0005_alter_client_client_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='client_id',
        ),
    ]
